//home
export const SIDEBAR_VISIBILITY_TOGGLE = 'SIDEBAR_VISIBILITY_TOGGLE'

//map
export const GET_USER_COORDINATES = "GET_USER_COORDINATES"

export const MARKERS_VISIBLITY_TOGGLE = 'MARKERS_VISIBLITY_TOGGLE'
export const MARKERS_MAKER_STATUS_TOGGLE = 'MARKERS_MAKER_STATUS_TOGGLE'

export const GET_MARKERS_REQUEST = 'GET_MARKERS_REQUEST'
export const GET_MARKERS_OK = 'GET_MARKERS_OK'
export const GET_MARKERS_ERROR = 'GET_MARKERS_ERROR'

export const SAVE_MARKERS_REQUEST = 'ADD_MARKER_REQUEST'
export const SAVE_MARKERS_OK = 'ADD_MARKER_OK'
export const SAVE_MARKERS_ERROR = 'ADD_MARKER_ERROR'

export const ADD_MARKER = 'ADD_MARKER'

export const DELETE_MARKER_FROM_SERVER_REQUEST = 'DELETE_MARKER_FROM_SERVER_REQUEST'
export const DELETE_MARKER_FROM_SERVER_OK = 'DELETE_MARKER_FROM_SERVER_OK'
export const DELETE_MARKER_FROM_SERVER_ERROR = 'DELETE_MARKER_FROM_SERVER_ERROR'
export const DELETE_MARKER_ONLY_FROM_UI = 'DELETE_MARKER_ONLY_FROM_UI'

export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE'

export const MARKERS_SAVE_REQUEST = 'MARKERS_SAVE_REQUEST'
export const MARKERS_SAVE_REQUEST_OK = 'MARKERS_SAVE_REQUEST_OK'
export const MARKERS_SAVE_REQUEST_NO = 'MARKERS_SAVE_REQUEST_NO'
export const MARKERS_SAVE_ERROR = 'MARKERS_SAVE_ERROR'

//user
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_OK = 'CREATE_USER_OK'
export const CREATE_USER_NO = 'CREATE_USER_NO'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_OK = 'LOGIN_USER_OK'
export const LOGIN_USER_NO = 'LOGIN_USER_NO'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const SESSION_USER_REQUEST = 'SESSION_USER_REQUEST'
export const SESSION_USER_OK = 'SESSION_USER_OK'
export const SESSION_USER_NO = 'SESSION_USER_NO'
export const SESSION_USER_ERROR = 'SESSION_USER_ERROR'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_OK = 'LOGOUT_USER_OK'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'

export const RESET_REGISTER_FLAG = 'RESET_REGISTER_FLAG'
export const RESET_USER_ERROR = 'RESET_USER_ERROR'
